apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: spring-boot-soap-monitor
  namespace: namespace2
spec:
  selector:
    matchLabels:
      app: helm-chart  # use the same label as in your deployment
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s