apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-boot-podmonitor
  labels:
    release: prometheus-operator   # same as above, matches Prometheus selector
spec:
  selector:
    matchLabels:
      app: helm-chart
  namespaceSelector:
    matchNames:
      - default    # Change if your pods are in another namespace
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scheme: http
