apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: spring-boot-prometheus-monitor
  namespace: namespace2
spec:
  selector:
    matchLabels:
      app: helm-chart  # matches your Deployment label
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
